### ISSUE TITLE
Links for the third Kokkos tea time are broken

### ISSUE THREAD

**Issue by tpadioleau** [CExA-project/CExA-project.github.io#13]

**Comment by cedricchevalier19** [comment]
Is it not fixed by #12?

**Comment by tpadioleau** [comment]
No I thought it would but it just added a button on the "news" page.

I don't understand what is happening to the links of this tea time.

**Comment by jbigot** [comment]
did you mean team time ? ;p

**Comment by tpadioleau** [comment]
I think I read the name of the file like 3 or 4 times. Completely missed this extra m. ^^'

**Comment by jbigot** [comment]
So would I have, hadn't I used copy & paste
