### ISSUE TITLE
Wrong links toward traning and coffees

### ISSUE THREAD

**Issue by xxirii** [CExA-project/CExA-project.github.io#17]
In this page : https://cexa-project.org/presentation/

The links:
- Second training
- CExA virtual café
point toward https://cexa-project.org/triclade/

This raises the question of:
- having a dedicated page for trainings and workshops?
- having a dedicated page for Kokkos Coffee and Teatime? Today the trainings, coffees and teatime are in the News timeline
- or simply points toward the News page?

**Comment by jbigot** [comment]
For now I made it point to news as an easy short term fix, maybe @jthelot or @Celiaioulain have a better idea
